// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightTypeDoc from "starlight-typedoc";
import starlightThemeRapide from "starlight-theme-rapide";
// Category-grouped API sidebar, generated by `bun run sidebar` (see
// scripts/gen-api-sidebar.mjs). starlight-typedoc's own sidebar can only group
// by reflection kind, so we build a `@group`-based one ourselves.
import apiSidebar from "./src/generated/api-sidebar.json" with { type: "json" };

// https://astro.build/config
export default defineConfig({
  integrations: [
    starlight({
      title: "agent-core",
      description: "A minimal, provider-agnostic agentic loop.",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/",
        },
      ],
      plugins: [
        // VS Code-inspired theme (cleaner palette + typography than default).
        starlightThemeRapide(),
        // Generates the API reference from the SDK's TSDoc during the build.
        starlightTypeDoc({
          entryPoints: ["../agent-core/index.ts"],
          tsconfig: "../tsconfig.json",
          output: "api",
          typeDoc: {
            // TypeDoc options
            excludeInternal: true,
            // starlight-typedoc builds its sidebar from TypeDoc *groups*, so we
            // drive grouping with `@group` tags in the source and order them
            // here — yielding Core / Tools / Memory / … instead of the default
            // kind buckets (Classes, Functions, …).
            groupOrder: [
              "Core",
              "Messages & Events",
              "Model",
              "Tools",
              "Memory",
              "Stop Conditions",
              "Permissions",
              "Credentials",
              "Composition",
              "Workflow",
              "Testing",
              "*",
            ],
            // typedoc-plugin-markdown options for readable output
            useCodeBlocks: true,
            expandObjects: true,
            parametersFormat: "table",
            propertiesFormat: "table",
            enumMembersFormat: "table",
            typeDeclarationFormat: "table",
            indexFormat: "table",
          },
        }),
      ],
      sidebar: [
        {
          label: "Guides",
          items: [
            { label: "Getting started", slug: "getting-started" },
            { label: "Concepts", slug: "concepts" },
          ],
        },
        {
          label: "API Reference",
          items: [{ label: "Overview", link: "/api/" }, ...apiSidebar],
        },
      ],
    }),
  ],
});
